### ISSUE TITLE
Upload to Hackage

### ISSUE THREAD

**Issue by pepeiborra** [mokus0/th-extras#10]
We (HLS) need a new version of this package with GHC 9 support.

**Comment by jneira** [comment]
Maybe @ryantrinkle could help this time too? thanks

**Comment by jneira** [comment]
I sent an email to see if the hls release [could be unblocked](https://github.com/haskell/haskell-language-server/issues/2281) but pinging here anyways
@ryantrinkle @mokus0 thanks in advance!

**Comment by jneira** [comment]
I've resent the email, asking maintainers to consider add some other hackage account to package uploaders if they are busy and offering myself to do it. My hackage account is https://hackage.haskell.org/user/jneira

**Comment by ali-abrar** [comment]
I think this can be closed: https://hackage.haskell.org/package/th-extras-0.0.0.5

**Comment by jneira** [comment]
many thanks for take care

**Comment by Ericson2314** [comment]
We can close this.

**Comment by jneira** [comment]
yeah, @pepeiborra could do it
