### ISSUE TITLE
Support GHC 9.4

### ISSUE THREAD

**Issue by ncfavier** [mokus0/th-extras#18]
AFAICT all that's needed is to relax the upper bound on `template-haskell`.

cc @Bodigrim @Ericson2314

**Comment by Bodigrim** [comment]
I'm not a maintainer here, but it's usually better to raise a PR with a bump, so that maintainers can just merge. If a PR remains unanswered for long time, you can raise a ticket at https://github.com/haskell-infra/hackage-trustees/issues.

**Comment by erikd** [comment]
https://github.com/mokus0/th-extras/pull/21 will cover this as well.

**Comment by andreasabel** [comment]
Fixed, please close.
